language: java
jdk:
- oraclejdk8
deploy:
  api_key:
    secure: dZTo9hTRH8hF3Izi9j6II+e5gEM9zHkoVdIeZsBbV1mPdQSFZN6fZqJjhEZuFx5JyM90eF/vXyexk7iF2LcRRhPbbZiwsRTbBamS73OYm1a70GPO0tZp60FiS136Mlh+xM8uOauf92gfQIs1PPxO9qrIt1YIG6Qlst+LIIQh3w4ysem2Ape4qWubu2jHnYtobPhKtlMcUxzdOnMEvPg4EGqDHRPFKzfto/xRBqPbeY1iKQ0cbBruVY3hclcF9KnPK8B0bA32UJDPcNsKHYLDaOvyAGdatp/LN8NYA8tQVVLl5ua2PSKIkxo46VcOhirBeqFZA57DWh01KP4l4xLbq0gS1jQS8c429PN8l/ehdxBP8+qW0SdEAdKa0RHZTIu5wNd/EDnktBwNymNbC4vzIHrcDXlZ6VsrzIki1Lmx9Ks8WE5jjLd45oK+DNOsSpNtazU37HjqfgUqs1VGrXmsfsiPfDsGbxZpHAEQA5SPDx+CsaKybEKf6r9Eur+Vr77F+VMdPYHeb2HRvd/UPsp498GciPk2bHrJcq2yJnJeYp2KcvAOssc9oylCnyz/sXxqlaNZkAmQs8z6RtYdktlUe8nhVclnFHWrIVP3HiXK0NFQynXA4Qc+9s/RCq1GMaV1CLzcuyWsf8SIz8Z0Ygl/upCVq/I/FlSwmqh8ErZNkE8=
